"""Render generated docs from the module registry (spec 0019, M0).

``make docs`` runs this: ``docs/OWNERSHIP.md`` (ownership + budgets, straight
from the registry) and ``docs/ARCHITECTURE.md`` (module table + live size
snapshot + stable kernel map) are generated, not remembered (principle 10).
Outputs stay gitignored; the docs gate is a smoke test (generator runs,
markers present), never a diff.

Usage:
    .venv/bin/python voiceai/tooling/render_docs.py [--out docs]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from voiceai.modules import ALL_MODULES  # noqa: E402

#: Stable kernel map: concern area → home. Lives here (not generated) because
#: the kernel moves on migration-spec timescales, not per-merge.
KERNEL_TABLE: tuple[tuple[str, str], ...] = (
    ("envelopes, errors, pagination, ids, logger, SSRF, keys", "voiceai/common/"),
    ("env, container, app factory, db, redis, bus, lifecycle, workers", "voiceai/core/"),
    ("BaseFields, collections, repositories, migrations", "voiceai/database/"),
    ("liveness, readiness, dependency report", "voiceai/modules/health/"),
)

GENERATED_BANNER = "<!-- GENERATED by `make docs` from the module registry + spec 0018. Do not hand-edit. -->"


def _module_rows() -> list[str]:
    """One markdown row per registered module, in registry order."""
    rows = []
    for module in ALL_MODULES:
        rows.append(
            f"| `{module.name}` | `{module.owner_squad}` | `{module.slack_channel}` "
            f"| `{module.runbook_path}` | {module.max_lines} |"
        )
    return rows


def _size_snapshot() -> list[str]:
    """Live over-800 list with debt owners, plus per-module totals vs budgets."""
    from tests.arch.test_size_budgets import DEBT_FILE_LINES, SIZE_DEBT

    lines = ["## Size snapshot (live)", ""]
    over = sorted(path for path in SIZE_DEBT)
    if over:
        lines.append("Over-800 files and their owning split specs:")
        lines.append("")
        for path in over:
            lines.append(f"- `{path}` → {SIZE_DEBT[path]}")
        lines.append("")
    lines.append("Module budgets (registry `max_lines`, enforced by test_size_budgets.py):")
    lines.append("")
    for module in ALL_MODULES:
        lines.append(f"- `{module.name}`: ≤ {module.max_lines} lines")
    lines.append("")
    lines.append(f"Hard file ceiling: {1500} lines, no exemptions. Target: {DEBT_FILE_LINES} with debt entries.")
    lines.append("")
    return lines


def render_ownership() -> str:
    """Render ``docs/OWNERSHIP.md`` from the registry."""
    parts = [
        GENERATED_BANNER,
        "# Ownership (generated from the registry — do not hand-edit)",
        "",
        "Source of truth: `voiceai/modules/__init__.py` (`ModuleDef`), pinned by",
        "`tests/arch/modules/test_registry.py`. Team decision: no CODEOWNERS /",
        "required-reviewer files; ownership is registry + docs.",
        "",
        "| Module | Squad | Slack | Runbook | Budget (lines) |",
        "|---|---|---|---|---|",
        *_module_rows(),
        "",
        "Rule: adding a module = scaffold + registry entry (name, owner, runbook,",
        "budget) + spec. The registry test fails when any entry lacks them.",
        "",
    ]
    return "\n".join(parts)


def render_architecture() -> str:
    """Render ``docs/ARCHITECTURE.md``: registry modules, kernel map, live sizes."""
    parts = [
        GENERATED_BANNER,
        "# Architecture (generated — see spec 0018 for the binding design)",
        "",
        "New code flows one way: `controller → service → repository → database`",
        "(AGENTS.md §3). Cross-module use goes through the target's `__all__`",
        "surface via the container — never deep imports.",
        "",
        "## Modules (registry)",
        "",
        "| Module | Squad | Slack | Runbook | Budget (lines) |",
        "|---|---|---|---|---|",
        *_module_rows(),
        "## Shared kernel (stable map)",
        "",
        "| Concern | Home |",
        "|---|---|",
    ]
    parts.extend(f"| {concern} | `{home}` |" for concern, home in KERNEL_TABLE)
    parts.append("")
    parts.extend(_size_snapshot())
    parts.append("Strangler rule: only `*/adapters/` may import legacy; legacy shims")
    parts.append("are pure re-exports tagged `# legacy-shim(spec-NNNN)` and die at cutover.")
    parts.append("")
    return "\n".join(parts)


def render(outdir: Path) -> None:
    """Write both generated docs into ``outdir``."""
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "OWNERSHIP.md").write_text(render_ownership(), encoding="utf-8")
    (outdir / "ARCHITECTURE.md").write_text(render_architecture(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """Entry point: ``--out`` defaults to the repo ``docs/`` directory."""
    parser = argparse.ArgumentParser(description="Render generated docs from the registry.")
    parser.add_argument("--out", default=str(REPO_ROOT / "docs"), help="Output directory.")
    args = parser.parse_args(argv)
    render(Path(args.out))
    print(f"rendered OWNERSHIP.md + ARCHITECTURE.md into {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
