"""Shared helper constants (env keys + defaults).

Single home for the environment key names and fallback values read across
``voiceai.helpers``. Call sites read them through ``core.environment`` —
never via ``os`` directly.
"""

from __future__ import annotations

CHECK_FOR_COMPLETION_LLM_ENV = "CHECK_FOR_COMPLETION_LLM"
TOOL_URL_HOST_ALLOWLIST_ENV = "VOICEAI_TOOL_URL_HOST_ALLOWLIST"
LANGUAGE_DETECTION_LLM_ENV = "LANGUAGE_DETECTION_LLM"
BUCKET_NAME_ENV = "BUCKET_NAME"
RECORDING_BUCKET_NAME_ENV = "RECORDING_BUCKET_NAME"
RECORDING_BUCKET_URL_ENV = "RECORDING_BUCKET_URL"
SONIOX_HOST_PROTOCOL_ENV = "SONIOX_HOST_PROTOCOL"
LANGUAGE_SWITCH_LLM_API_KEY_ENV = "LANGUAGE_SWITCH_LLM_API_KEY"
LANGUAGE_SWITCH_LLM_API_BASE_ENV = "LANGUAGE_SWITCH_LLM_API_BASE"
LANGUAGE_SWITCH_LLM_API_VERSION_ENV = "LANGUAGE_SWITCH_LLM_API_VERSION"
AZURE_OPENAI_API_KEY_ENV = "AZURE_OPENAI_API_KEY"
AZURE_OPENAI_ENDPOINT_ENV = "AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_API_VERSION_ENV = "AZURE_OPENAI_API_VERSION"
ANTHROPIC_API_KEY_ENV = "ANTHROPIC_API_KEY"
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
LANGUAGE_SWITCH_LLM_ENV = "LANGUAGE_SWITCH_LLM"
AWS_REGION_ENV = "AWS_REGION"
LANGUAGE_SWITCH_HEDGE_AFTER_S_ENV = "LANGUAGE_SWITCH_HEDGE_AFTER_S"

# Static fallbacks (dynamic ones such as llm.model stay inline at call sites).
DEFAULT_LANGUAGE_DETECTION_LLM = "gpt-4.1-mini"
DEFAULT_SONIOX_HOST_PROTOCOL = "wss"
DEFAULT_AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
