"""Persistence seam for the platform module (Constitution I, contract L-03).

:class:`PlatformRepository` is the neutral persistence interface services
program against: CRUD and filtered queries only, no business rules. The
shipped ``MemoryStore``/``RedisStore`` (in this package) already share this
shape and satisfy the Protocol structurally — no adapters needed. The
Mongo backend (database cutover) implements this same Protocol, which is
why every signature here is pinned exactly.

Method signatures below mirror ``store.MemoryStore`` verbatim.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from voiceai.platform.models import (
    ApiKey,
    AuthEvent,
    Batch,
    Execution,
    GraphDoc,
    GraphVersion,
    InboundConfig,
    Integration,
    Invite,
    KnowledgeBase,
    LedgerEntry,
    Organization,
    PhoneNumber,
    SessionRecord,
    SubAccount,
    Tool,
    User,
    VectorStoreConfig,
    VoiceEntry,
    Wallet,
    Webhook,
    WorkflowCampaign,
    WorkflowDoc,
    WorkflowRun,
    WorkflowVersion,
)

__all__ = ["PlatformRepository"]


@runtime_checkable
class PlatformRepository(Protocol):
    """Neutral persistence interface (see module docstring)."""

    async def save_execution(self, execution: Execution) -> None: ...

    async def get_execution(self, execution_id: str) -> Optional[Execution]: ...

    async def count_executions(
        self,
        agent_id: Optional[str] = None,
        batch_id: Optional[str] = None,
        status: Optional[str] = None,
        direction: Optional[str] = None,
        since: Any = None,
        org_id: Optional[str] = None,
    ) -> int: ...

    async def list_executions(
        self,
        agent_id: Optional[str] = None,
        batch_id: Optional[str] = None,
        status: Optional[str] = None,
        limit: int = 50,
        offset: int = 0,
        direction: Optional[str] = None,
        since: Any = None,
        include_transcript: bool = True,
        org_id: Optional[str] = None,
    ) -> List[Execution]: ...

    async def aggregate_execution_stats(
        self,
        agent_id: Optional[str] = None,
        since: Any = None,
        max_scan: int = 5000,
        org_id: Optional[str] = None,
    ) -> Dict[str, Any]: ...

    async def aggregate_latency_stats(
        self,
        agent_id: Optional[str] = None,
        since: Any = None,
        max_scan: int = 5000,
        org_id: Optional[str] = None,
    ) -> Dict[str, Any]: ...

    async def save_batch(self, batch: Batch) -> None: ...

    async def get_batch(self, batch_id: str) -> Optional[Batch]: ...

    async def list_batches(self, agent_id: Optional[str] = None, org_id: Optional[str] = None) -> List[Batch]: ...

    async def set_batch_talko_key(self, batch_id: str, talko_api_key: str) -> None: ...

    async def get_batch_talko_key(self, batch_id: str) -> Optional[str]: ...

    async def clear_batch_talko_key(self, batch_id: str) -> None: ...

    async def try_claim_batch_start(
        self, batch_id: str, idempotency_key: Optional[str] = None
    ) -> tuple["Batch", bool]: ...

    async def delete_batch(self, batch_id: str) -> bool: ...

    async def delete_executions_for_batch(self, batch_id: str, org_id: Optional[str] = None) -> int: ...

    async def save_number(self, number: PhoneNumber) -> None: ...

    async def get_number(self, number_id: str) -> Optional[PhoneNumber]: ...

    async def list_numbers(self) -> List[PhoneNumber]: ...

    async def delete_number(self, number_id: str) -> bool: ...

    async def save_kb(self, kb: KnowledgeBase) -> None: ...

    async def get_kb(self, kb_id: str) -> Optional[KnowledgeBase]: ...

    async def list_kbs(self) -> List[KnowledgeBase]: ...

    async def delete_kb(self, kb_id: str) -> bool: ...

    async def save_tool(self, tool: Tool) -> None: ...

    async def get_tool(self, tool_id: str) -> Optional[Tool]: ...

    async def list_tools(self, agent_id: Optional[str] = None, org_id: Optional[str] = None) -> List[Tool]: ...

    async def delete_tool(self, tool_id: str) -> bool: ...

    async def save_webhook(self, hook: Webhook) -> None: ...

    async def get_webhook(self, webhook_id: str) -> Optional[Webhook]: ...

    async def list_webhooks(self, org_id: Optional[str] = None) -> List[Webhook]: ...

    async def delete_webhook(self, webhook_id: str) -> bool: ...

    async def save_inbound(self, config: InboundConfig) -> None: ...

    async def get_inbound(self, agent_id: str) -> Optional[InboundConfig]: ...

    async def save_voice(self, voice: VoiceEntry) -> None: ...

    async def list_voices(self, agent_id: Optional[str] = None) -> List[VoiceEntry]: ...

    async def delete_voice(self, voice_id: str) -> bool: ...

    async def save_vector_config(self, agent_id: str, config: VectorStoreConfig) -> None: ...

    async def get_vector_config(self, agent_id: str) -> Optional[VectorStoreConfig]: ...

    async def save_sub_account(self, sub: SubAccount) -> None: ...

    async def get_sub_account(self, sub_id: str) -> Optional[SubAccount]: ...

    async def list_sub_accounts(self) -> List[SubAccount]: ...

    async def delete_sub_account(self, sub_id: str) -> bool: ...

    async def save_integration(self, integration: Integration) -> None: ...

    async def get_integration(self, integration_id: str) -> Optional[Integration]: ...

    async def list_integrations(self) -> List[Integration]: ...

    async def delete_integration(self, integration_id: str) -> bool: ...

    async def save_graph(self, graph: GraphDoc) -> None: ...

    async def get_graph(self, graph_id: str) -> Optional[GraphDoc]: ...

    async def list_graphs(self) -> List[GraphDoc]: ...

    async def delete_graph(self, graph_id: str) -> bool: ...

    async def save_graph_version(self, version: GraphVersion) -> None: ...

    async def list_graph_versions(self, graph_id: str) -> List[GraphVersion]: ...

    async def save_workflow(self, workflow: WorkflowDoc) -> None: ...

    async def get_workflow(self, workflow_id: str) -> Optional[WorkflowDoc]: ...

    async def list_workflows(self) -> List[WorkflowDoc]: ...

    async def delete_workflow(self, workflow_id: str) -> bool: ...

    async def save_workflow_version(self, version: WorkflowVersion) -> None: ...

    async def list_workflow_versions(self, workflow_id: str) -> List[WorkflowVersion]: ...

    async def save_workflow_run(self, run: WorkflowRun) -> None: ...

    async def get_workflow_run(self, run_id: str) -> Optional[WorkflowRun]: ...

    async def list_workflow_runs(self, campaign_id: Optional[str] = None) -> List[WorkflowRun]: ...

    async def save_campaign(self, campaign: WorkflowCampaign) -> None: ...

    async def get_campaign(self, campaign_id: str) -> Optional[WorkflowCampaign]: ...

    async def list_campaigns(self) -> List[WorkflowCampaign]: ...

    async def get_organization(self) -> Organization: ...

    async def save_organization(self, org: Organization) -> None: ...

    async def save_api_key(self, key: ApiKey) -> None: ...

    async def get_api_key_by_hash(self, digest: str) -> Optional[ApiKey]: ...

    async def list_api_keys(self) -> List[ApiKey]: ...

    async def delete_api_key(self, key_id: str) -> bool: ...

    async def delete_user_api_keys(self, user_id: str) -> int: ...

    async def save_user(self, user: User) -> None: ...

    async def get_user(self, user_id: str) -> Optional[User]: ...

    async def get_user_by_email(self, email: str) -> Optional[User]: ...

    async def list_users(self) -> List[User]: ...

    async def count_users(self) -> int: ...

    async def delete_user(self, user_id: str) -> bool: ...

    async def save_session(self, session: SessionRecord) -> None: ...

    async def get_session(self, token_hash: str) -> Optional[SessionRecord]: ...

    async def delete_session(self, token_hash: str) -> bool: ...

    async def delete_user_sessions(self, user_id: str) -> int: ...

    async def delete_user_sessions_except(self, user_id: str, keep: set) -> int: ...

    async def save_invite(self, invite: Invite) -> None: ...

    async def get_invite(self, invite_id: str) -> Optional[Invite]: ...

    async def get_invite_by_token_hash(self, digest: str) -> Optional[Invite]: ...

    async def list_invites(self) -> List[Invite]: ...

    async def delete_invite(self, invite_id: str) -> bool: ...

    async def add_auth_event(self, event: AuthEvent) -> None: ...

    async def list_auth_events(self, limit: int = 100) -> List[AuthEvent]: ...

    async def reset_platform(self) -> Dict[str, int]: ...

    async def get_wallet(self) -> Wallet: ...

    async def save_wallet(self, wallet: Wallet) -> None: ...

    async def topup_wallet_credits(self, amount: Decimal, reason: Optional[str] = None) -> Wallet: ...

    async def debit_wallet_credits(self, amount: Decimal, reason: Optional[str] = None) -> Wallet: ...

    async def add_ledger_entry(self, entry: LedgerEntry) -> None: ...

    async def list_ledger(self, limit: int = 50, entry_type: Optional[str] = None) -> List[LedgerEntry]: ...
